services:
  mysqldb:
    image: mysql:8
    container_name: mysqlcontainer
    restart: unless-stopped
    volumes:
      - ./database/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: letmein
